/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CatalogCountsApplyConfiguration represents a declarative configuration of the CatalogCounts type for use
// with apply.
//
// CatalogCounts contains the number of tools, resources, and prompt templates
// reported by the MCP server via list calls after a successful handshake.
type CatalogCountsApplyConfiguration struct {
	// ToolCount is the number of tools reported by the server.
	// Nil when the server does not support tools.
	ToolCount *int32 `json:"toolCount,omitempty"`
	// ResourceCount is the number of resources reported by the server.
	// Nil when the server does not support resources.
	ResourceCount *int32 `json:"resourceCount,omitempty"`
	// PromptCount is the number of prompt templates reported by the server.
	// Nil when the server does not support prompts.
	PromptCount *int32 `json:"promptCount,omitempty"`
}

// CatalogCountsApplyConfiguration constructs a declarative configuration of the CatalogCounts type for use with
// apply.
func CatalogCounts() *CatalogCountsApplyConfiguration {
	return &CatalogCountsApplyConfiguration{}
}

// WithToolCount sets the ToolCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ToolCount field is set to the value of the last call.
func (b *CatalogCountsApplyConfiguration) WithToolCount(value int32) *CatalogCountsApplyConfiguration {
	b.ToolCount = &value
	return b
}

// WithResourceCount sets the ResourceCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceCount field is set to the value of the last call.
func (b *CatalogCountsApplyConfiguration) WithResourceCount(value int32) *CatalogCountsApplyConfiguration {
	b.ResourceCount = &value
	return b
}

// WithPromptCount sets the PromptCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromptCount field is set to the value of the last call.
func (b *CatalogCountsApplyConfiguration) WithPromptCount(value int32) *CatalogCountsApplyConfiguration {
	b.PromptCount = &value
	return b
}
