/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// GatewayConfigApplyConfiguration represents a declarative configuration of the GatewayConfig type for use
// with apply.
//
// GatewayConfig configures gateway integration.
// When set on MCPServerSpec, the operator creates an HTTPRoute attaching
// the MCPServer's Service to the referenced Gateway.
type GatewayConfigApplyConfiguration struct {
	// ParentRef identifies the Gateway to attach the HTTPRoute to.
	ParentRef *GatewayParentRefApplyConfiguration `json:"parentRef,omitempty"`
	// Hostname is the DNS hostname for the HTTPRoute.
	// When set, the HTTPRoute's hostnames field is populated with this value,
	// enabling host-based routing at the Gateway.
	// Example: my-mcp-server.mcp.local
	Hostname *string `json:"hostname,omitempty"`
}

// GatewayConfigApplyConfiguration constructs a declarative configuration of the GatewayConfig type for use with
// apply.
func GatewayConfig() *GatewayConfigApplyConfiguration {
	return &GatewayConfigApplyConfiguration{}
}

// WithParentRef sets the ParentRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParentRef field is set to the value of the last call.
func (b *GatewayConfigApplyConfiguration) WithParentRef(value *GatewayParentRefApplyConfiguration) *GatewayConfigApplyConfiguration {
	b.ParentRef = value
	return b
}

// WithHostname sets the Hostname field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hostname field is set to the value of the last call.
func (b *GatewayConfigApplyConfiguration) WithHostname(value string) *GatewayConfigApplyConfiguration {
	b.Hostname = &value
	return b
}
