/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPServerCardApplyConfiguration represents a declarative configuration of the MCPServerCard type for use
// with apply.
//
// MCPServerCard is a structured summary of the MCP server's identity,
// endpoint, capabilities, and user-provided metadata. It aggregates
// information from the handshake result and spec into a single
// discoverable object in status.
type MCPServerCardApplyConfiguration struct {
	// Name is the server's self-reported name from the handshake.
	Name *string `json:"name,omitempty"`
	// Version is the server's self-reported version.
	Version *string `json:"version,omitempty"`
	// ProtocolVersion is the negotiated MCP protocol version.
	ProtocolVersion *string `json:"protocolVersion,omitempty"`
	// Address is the cluster-internal service URL for the MCP server.
	Address *string `json:"address,omitempty"`
	// Capabilities lists which MCP protocol features the server supports.
	Capabilities *MCPServerCapabilitiesApplyConfiguration `json:"capabilities,omitempty"`
	// Labels are the user-provided extraLabels from the MCPServer spec,
	// surfaced here for external discovery.
	Labels map[string]string `json:"labels,omitempty"`
	// Annotations are the user-provided extraAnnotations from the MCPServer spec,
	// surfaced here for external discovery.
	Annotations map[string]string `json:"annotations,omitempty"`
}

// MCPServerCardApplyConfiguration constructs a declarative configuration of the MCPServerCard type for use with
// apply.
func MCPServerCard() *MCPServerCardApplyConfiguration {
	return &MCPServerCardApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MCPServerCardApplyConfiguration) WithName(value string) *MCPServerCardApplyConfiguration {
	b.Name = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *MCPServerCardApplyConfiguration) WithVersion(value string) *MCPServerCardApplyConfiguration {
	b.Version = &value
	return b
}

// WithProtocolVersion sets the ProtocolVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolVersion field is set to the value of the last call.
func (b *MCPServerCardApplyConfiguration) WithProtocolVersion(value string) *MCPServerCardApplyConfiguration {
	b.ProtocolVersion = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *MCPServerCardApplyConfiguration) WithAddress(value string) *MCPServerCardApplyConfiguration {
	b.Address = &value
	return b
}

// WithCapabilities sets the Capabilities field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capabilities field is set to the value of the last call.
func (b *MCPServerCardApplyConfiguration) WithCapabilities(value *MCPServerCapabilitiesApplyConfiguration) *MCPServerCardApplyConfiguration {
	b.Capabilities = value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *MCPServerCardApplyConfiguration) WithLabels(entries map[string]string) *MCPServerCardApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *MCPServerCardApplyConfiguration) WithAnnotations(entries map[string]string) *MCPServerCardApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
