/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPServerSpecApplyConfiguration represents a declarative configuration of the MCPServerSpec type for use
// with apply.
//
// MCPServerSpec defines the desired state of MCPServer.
type MCPServerSpecApplyConfiguration struct {
	// Source is a required field that defines where the MCP server should be sourced from.
	// Currently supports container images, with potential for additional source types in the future.
	// This configuration determines how the MCP server will be deployed and run.
	Source *SourceApplyConfiguration `json:"source,omitempty"`
	// Config is a required field that defines how the MCP server should be configured when it runs.
	// This includes runtime settings such as the server port, command-line arguments,
	// environment variables, and storage mounts.
	Config *ServerConfigApplyConfiguration `json:"config,omitempty"`
	// Labels are applied to the Deployment, PodTemplate, and Service.
	Labels map[string]string `json:"labels,omitempty"`
	// Annotations are applied to the Deployment, PodTemplate, and Service.
	Annotations map[string]string `json:"annotations,omitempty"`
	// Runtime defines runtime management configuration.
	// If not specified, default runtime settings will be applied.
	Runtime *RuntimeConfigApplyConfiguration `json:"runtime,omitempty"`
}

// MCPServerSpecApplyConfiguration constructs a declarative configuration of the MCPServerSpec type for use with
// apply.
func MCPServerSpec() *MCPServerSpecApplyConfiguration {
	return &MCPServerSpecApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithSource(value *SourceApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithConfig(value *ServerConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *MCPServerSpecApplyConfiguration) WithLabels(entries map[string]string) *MCPServerSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *MCPServerSpecApplyConfiguration) WithAnnotations(entries map[string]string) *MCPServerSpecApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithRuntime sets the Runtime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Runtime field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithRuntime(value *RuntimeConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Runtime = value
	return b
}
