/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPServerSpecApplyConfiguration represents a declarative configuration of the MCPServerSpec type for use
// with apply.
//
// MCPServerSpec defines the desired state of MCPServer.
type MCPServerSpecApplyConfiguration struct {
	// ExtraLabels are applied to the Deployment metadata, PodTemplate metadata, and Service metadata.
	// The operator-managed keys "app" and "mcp-server" cannot be overridden.
	ExtraLabels map[string]string `json:"extraLabels,omitempty"`
	// ExtraAnnotations are applied to the Deployment metadata, PodTemplate metadata, and Service metadata.
	ExtraAnnotations map[string]string `json:"extraAnnotations,omitempty"`
	// WorkloadRef references an external Deployment, DaemonSet, or StatefulSet
	// in the same namespace. When set, the operator monitors the referenced
	// workload read-only and never creates its own Deployment.
	// Mutually exclusive with source and operator-managed workload fields.
	WorkloadRef *WorkloadReferenceApplyConfiguration `json:"workloadRef,omitempty"`
	// ServiceRef references an external Service in the same namespace.
	// When set, the operator skips Service creation and uses the referenced
	// Service for the MCP endpoint URL.
	ServiceRef *ServiceReferenceApplyConfiguration `json:"serviceRef,omitempty"`
	// Source defines where the MCP server should be sourced from.
	// Currently supports container images, with potential for additional source types in the future.
	// Required when workloadRef is not set.
	Source *SourceApplyConfiguration `json:"source,omitempty"`
	// Config defines how the MCP server should be configured when it runs.
	// This includes runtime settings such as the server port, command-line arguments,
	// environment variables, and storage mounts.
	// May be omitted in BYO mode when workloadRef and serviceRef are set.
	Config *ServerConfigApplyConfiguration `json:"config,omitempty"`
	// Runtime defines runtime management configuration.
	// If not specified, default runtime settings will be applied.
	Runtime *RuntimeConfigApplyConfiguration `json:"runtime,omitempty"`
	// MCP defines Model Context Protocol specific properties of the server.
	// This section describes the MCP server's protocol-level behavior,
	// as opposed to how it is sourced, configured, or managed at runtime.
	MCP *MCPConfigApplyConfiguration `json:"mcp,omitempty"`
	// Network configures network policies for the MCP server pod.
	Network *NetworkConfigApplyConfiguration `json:"network,omitempty"`
	// Transport configures transport-layer settings for
	// operator-to-MCP-server communication.
	Transport *TransportConfigApplyConfiguration `json:"transport,omitempty"`
}

// MCPServerSpecApplyConfiguration constructs a declarative configuration of the MCPServerSpec type for use with
// apply.
func MCPServerSpec() *MCPServerSpecApplyConfiguration {
	return &MCPServerSpecApplyConfiguration{}
}

// WithExtraLabels puts the entries into the ExtraLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraLabels field,
// overwriting an existing map entries in ExtraLabels field with the same key.
func (b *MCPServerSpecApplyConfiguration) WithExtraLabels(entries map[string]string) *MCPServerSpecApplyConfiguration {
	if b.ExtraLabels == nil && len(entries) > 0 {
		b.ExtraLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraLabels[k] = v
	}
	return b
}

// WithExtraAnnotations puts the entries into the ExtraAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExtraAnnotations field,
// overwriting an existing map entries in ExtraAnnotations field with the same key.
func (b *MCPServerSpecApplyConfiguration) WithExtraAnnotations(entries map[string]string) *MCPServerSpecApplyConfiguration {
	if b.ExtraAnnotations == nil && len(entries) > 0 {
		b.ExtraAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExtraAnnotations[k] = v
	}
	return b
}

// WithWorkloadRef sets the WorkloadRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadRef field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithWorkloadRef(value *WorkloadReferenceApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.WorkloadRef = value
	return b
}

// WithServiceRef sets the ServiceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceRef field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithServiceRef(value *ServiceReferenceApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.ServiceRef = value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithSource(value *SourceApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithConfig(value *ServerConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithRuntime sets the Runtime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Runtime field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithRuntime(value *RuntimeConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Runtime = value
	return b
}

// WithMCP sets the MCP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MCP field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithMCP(value *MCPConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.MCP = value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithNetwork(value *NetworkConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Network = value
	return b
}

// WithTransport sets the Transport field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Transport field is set to the value of the last call.
func (b *MCPServerSpecApplyConfiguration) WithTransport(value *TransportConfigApplyConfiguration) *MCPServerSpecApplyConfiguration {
	b.Transport = value
	return b
}
