/*
Copyright 2026 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MCPServerStatusApplyConfiguration represents a declarative configuration of the MCPServerStatus type for use
// with apply.
//
// MCPServerStatus defines the observed state of MCPServer.
type MCPServerStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation most recently observed by the controller.
	// This allows users to determine if the status reflects the latest spec changes.
	// When observedGeneration matches metadata.generation, the status is up-to-date.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// DeploymentName is the name of the Deployment created for this MCPServer.
	DeploymentName *string `json:"deploymentName,omitempty"`
	// ServiceName is the name of the Service created for this MCPServer.
	ServiceName *string `json:"serviceName,omitempty"`
	// Address contains the address of the MCP server service.
	Address *MCPServerAddressApplyConfiguration `json:"address,omitempty"`
	// ServerInfo contains identity and capability information reported by the
	// MCP server during the protocol handshake (initialize or server/discover).
	// This field is populated only after a successful handshake.
	ServerInfo *MCPServerInfoApplyConfiguration `json:"serverInfo,omitempty"`
	// Replicas is the total number of desired pods targeted by the owned Deployment.
	Replicas *int32 `json:"replicas,omitempty"`
	// ReadyReplicas is the number of pods targeted by the owned Deployment with a Ready condition.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// Conditions represent the latest available observations of the MCPServer's state.
	//
	// Standard condition types:
	//
	// - "Accepted": Configuration is valid and all referenced resources exist.
	// Reasons: Valid (True), Invalid (False with details in message).
	//
	// - "Available": Workload is running and dependent resources (Deployment,
	// Service, NetworkPolicy) are reconciled.
	// Reasons:
	// - Available: At least one replica is ready (Status=True)
	// - DeploymentUnavailable: No healthy instances
	// - ServiceUnavailable: Service could not be reconciled
	// - NetworkPolicyUnavailable: NetworkPolicy could not be reconciled
	// - ScaledToZero: Deployment scaled to 0 replicas
	// - Initializing: Waiting for initial status
	// - ConfigurationInvalid: Accepted=False, cannot proceed
	//
	// - "Verified": MCP endpoint completed the protocol handshake.
	// Reasons:
	// - Verified: Handshake succeeded (Status=True)
	// - NotVerified: Handshake has not been attempted yet (Status=Unknown)
	// - EndpointUnavailable: Handshake failed (Status=False)
	// - AuthSkipped: Endpoint returned 401/403, treated as reachable
	//
	// Specific failure details (ImagePullBackOff, OOMKilled, CrashLoop, etc.)
	// are included in the condition message, not the reason.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// MCPServerStatusApplyConfiguration constructs a declarative configuration of the MCPServerStatus type for use with
// apply.
func MCPServerStatus() *MCPServerStatusApplyConfiguration {
	return &MCPServerStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithObservedGeneration(value int64) *MCPServerStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithDeploymentName sets the DeploymentName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentName field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithDeploymentName(value string) *MCPServerStatusApplyConfiguration {
	b.DeploymentName = &value
	return b
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithServiceName(value string) *MCPServerStatusApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithAddress(value *MCPServerAddressApplyConfiguration) *MCPServerStatusApplyConfiguration {
	b.Address = value
	return b
}

// WithServerInfo sets the ServerInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServerInfo field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithServerInfo(value *MCPServerInfoApplyConfiguration) *MCPServerStatusApplyConfiguration {
	b.ServerInfo = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithReplicas(value int32) *MCPServerStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *MCPServerStatusApplyConfiguration) WithReadyReplicas(value int32) *MCPServerStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MCPServerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MCPServerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
